#!/usr/bin/env node

// This is a wrapper script that uses the connector to communicate with the persistent server
import { UnifiedIntelligenceConnector } from './src/connector.js';

const connector = new UnifiedIntelligenceConnector();
connector.run().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});