embedding_service:
  redis:
    url: "redis://:${REDIS_PASSWORD}@localhost:6379/0"
    stream_key: "${INSTANCE_ID}:events"
  
  # Provider configuration
  providers:
    primary:
      provider: "openai"
      api_key_source: "redis"  # or "env"
      api_key_field: "config:openai_api_key"
      model: "text-embedding-3-small"
      dimensions: 1536
      rate_limit_rps: 10
    
    fallback:
      provider: "groq"
      api_key_source: "redis"
      api_key_field: "config:groq_api_key"
      model: "llama3-8b-8192"  # Used for semantic feature extraction
      enabled: true
      retry_after_minutes: 5
  
  # Fallback strategy
  fallback_strategy:
    enable_fallback: true
    primary_failure_threshold: 3  # Switch to fallback after N failures
    track_provider_metrics: true
    fallback_on_rate_limit: true
    fallback_on_timeout: true
    fallback_on_api_error: true
  
  # Processing configuration
  processing:
    max_retries: 3
    retry_backoff_base: 60   # seconds
    max_retry_delay: 300     # seconds
    batch_size: 10
    rate_limit_delay: 0.1    # 100ms between API calls
  
  # Monitoring
  monitoring:
    metrics_interval: 60     # seconds
    log_level: "INFO"
    track_provider_usage: true
    alert_on_fallback: true
  
  # Consumer configuration
  consumer:
    group_name: "embedding_processors"
    consumer_prefix: "embedder"